stages:
- build_homepage
- code_coverage
- code_coverage_print


cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - build/
    - XerusTest

job_build_homepage:
  stage: build_homepage
  script: "cp .gitlab-ci-configs/.config.mk.ci.gcc config.mk; make -C doc doc && scp -r doc/html xerusweb:libxerus.org-443"
  when: always
  only: 
    - master
  allow_failure: true


job_code_coverage:
  stage: code_coverage
  script: "pwd; g++ --version; cp .gitlab-ci-configs/.config.mk.ci.gcc config.mk; mkdir -p build; make test &> build/build_output.txt || tail -n 200 build/build_output.txt; tail -n 200 build/build_output.txt"
  when: always

job_code_coverage_print:
  stage: code_coverage_print
  script: "echo 'debug.txt'; cat build/debug.txt; echo 'build_output.txt'; cat build/build_output.txt"
  when: always

