stages:
- build_homepage
- code_coverage
- code_coverage_print
- build_python2
- build_python3
- test_python2
- test_python3
- build_clang
- test_clang

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - build/
    - XerusTest

job_build_homepage:
  stage: build_homepage
  script: "cp .gitlab-ci-configs/.config.mk.ci.gcc config.mk; make -C doc doc && scp -r doc/html xerusweb:libxerus.org-443"
  when: always
  only: 
    - master
  allow_failure: true

job_code_coverage:
  stage: code_coverage
  script: "g++ --version; cp .gitlab-ci-configs/.config.mk.ci.gcc config.mk; make test &> build/debug.txt; tail -100 build/debug.txt; tail -100 build/build_output.txt"
  when: always

job_code_coverage_print:
  stage: code_coverage_print
  script: "cat build/build_output.txt"
  when: always

job_build_python2:
  stage: build_python2
  script: "g++ --version; cp .gitlab-ci-configs/.config.mk.ci.gcc.python config.mk; make python2"
  when: always

job_build_python3:
  stage: build_python3
  script: "g++ --version; cp .gitlab-ci-configs/.config.mk.ci.gcc.python config.mk; make python3"
  when: always

job_test_python2:
  stage: test_python2
  script: "g++ --version; cp .gitlab-ci-configs/.config.mk.ci.gcc.python config.mk; make test_python2"
  when: always

#job_test_python3:
#  stage: test_python3
#  script: "g++ --version; cp .config.mk.ci.gcc.python config.mk; make test_python3"
#  when: always

job_make_clang:
  stage: build_clang
  script: "clang++ --version; cp .gitlab-ci-configs/.config.mk.ci.clang config.mk; make XerusTest"
  when: always

job_test_clang:
  stage: test_clang
  script: "echo $CI_COMMIT_SHA; ./XerusTest all"

