package:
  name: xerus
  version: "4.0.1"

source:
  git_url: https://github.com/libxerus/xerus.git
  git_tag: conda

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - openblas
    - suitesparse
    - lapack
    - boost=1.69.0
    - python=3.7
    - binutils
    - openmp

  run:
    - openblas
    - suitesparse
    - lapack
    - boost=1.69.0
    - python=3.7
    - binutils
    - openmp

build:
  # already linked relative to $ORIGIN, so we need to turn
  # off conda's relocation mechanism because it screws it up
  binary_relocation: false

about:
  home: https://git.hemio.de/xerus/xerus.git
  license: AGPL v3.0
