{% set name = "Xerus" %}
{% set version = "4.0.1" %}
{% set branch = "conda" %}

package:
  name: {{ name|lower + '_' + branch|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/libxerus/xerus.git
    git_tag: {{ branch }}
    folder: xerus

build:
  number: 1
  skip: true       # [py<34 or win]
  run_exports:
    strong:
      - python
      - numpy
      - openblas
      - suitesparse
      - lapack
      - liblapacke
      - boost-cpp
      - libgomp

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - python {{ python }}
    - pip >=18.1
  host:
    - python
    - numpy
    - openblas
    - suitesparse
    - lapack
    - liblapacke
    - boost-cpp
    - libgomp
  run:
    - python
    - numpy
    - openblas
    - suitesparse
    - lapack
    - liblapacke
    - boost-cpp
    - libgomp

test:
  # requires:
  #   - pytest  # pytest xerus/src/pyTests
  files:
    - VERSION
  source_files:
    - xerus/src/pyTests

about:
  home: https://git.hemio.de/xerus/xerus.git
  license: "AGPL 3.0"
  license_file: LICENSE
  summary: "A c++ library for numerical calculations with higher order tensors"
  description: |
    The Xerus library is a general purpose library for numerical calculations with higher order tensors, Tensor-Train Decompositions / Matrix Product States and other Tensor Networks.
    The focus of development was the simple usability and adaptibility to any setting that requires higher order tensors or decompositions thereof.
  doc_url: https://www.libxerus.org/
  dev_url: https://git.hemio.de/xerus/xerus

extra:
  recipe-maintainers:
    - trunschk
